SELECT
    l1.ID,
    l1.BODYTYPE as TYPE,
    l1.ENGLISHNAME as NAME,
    coalesce(l2.ENGLISHNAME, l1.ENGLISHNAME) as PLANETARY_SYSTEM,
    l1.MEANRADIUS as MEAN_RADIUS,
    l1.SEMIMAJORAXIS * 6.68458712e-9 as SEMIMAJOR_ORBIT
FROM ANDY.PLUTO_CODE_ALONG.BODIES as l1
LEFT JOIN ANDY.PLUTO_CODE_ALONG.BODIES AS l2 ON l1.AROUNDPLANET_PLANET = l2.ID
WHERE
    l1.BODYTYPE IN ('Star', 'Planet', 'Dwarf Planet', 'Moon')
